### PR TITLE
update readme - steps to create and execute a mongo container

### PR DESCRIPTION
**Pull request by jonny-dungeons**
This may reduce friction for developers who are novices with database/containers etc. Btw, great project. I really like this and I am using it as a model to look at for my own project called ludwig.

### CODE REVIEW

**Comment by MiladSadeghi** [comment]
Thanks for contributing to this project! i ask because i want to understand for my own knowledge. why should a developer use docker in that situation? you can review the code for setting up an admin account. perhaps working with docker in a non-dockerized app could be challenging for a developer.

**Comment by jonny-dungeons** [comment]
I appreciate your quick reply back. Firstly, I wanna applaud you for your chatter app. It is clean, well designed and well documented.

Why docker?
1. Avoid installing mongo directly on our machine and consuming disk space 
2. It is stupid simple to spin up and tear down

On your point of reviewing code to set up a user account, sure, ok. But why is an engineer gonna wanna waste the time? I am a strong believer in making project stupid simple to spin up and tear down, whether the forker is a professional or a novice.

On your point of developer challenges - not a practical argument  - if a developer need to go through your code, have database knowledge, etc, then you are already attributing intelligence to the developer and docker is a trivial learning curve.

Irrespective, if you take my MR or leave it, I want to applaud you for your very clean code, design patterns and very clean design. Chatter is somethiing I am going to reference when building chat into my boilerplate. 

[My application Ludwig](https://github.com/mydungeon/ludwig) is a boilerplate which I am creating and I am just beginning to mess around with chat. I am choosing a path which is not socket.io. Just working with the native Websocket so I am going to use your app as a reference cuz I am new to websockets and am doing some things which are causing some unexpected behavior. 

My honest opinion is you should ditch socket.io client and go native.

I'd love for you to fork my app, mess around with it and give me some pointers on the chat websocket side of things.

**Comment by MiladSadeghi** [comment]
@mydungeon  Oh, okay, nice! thank you for your explanation and suggestions. im currently working on a PWA app and im interested in incorporating websockets into it. however, i lack knowledge about websockets and how they working. this project is quite old, and at that time, I simply wanted to build a MERN stack app :).

But after hearing your explanation, I realize the importance of improving my understanding of websockets. thank you for highlighting that. In the future, I plan to develop another chat app using Next.js 14, and I promise it will be better.

once again, thank you for your valuable suggestions!

**Comment by jonny-dungeons** [comment]
Good to know you intend to incorporate websocket on your PWA app. I'd be interested in what knowledge we can share as we are both learning through this tech. Keep in touch and again, I encourage you to clone or fork my [Ludwig repo](https://github.com/jonny-dungeons/ludwig) but understand if you are too busy.

**Pull request merged**
